spring:
  datasource: # DB 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

file:
  upload:
    location: src/main/resources/files/